// Training puzzles. Puzzle text uses standard chess terminology so it works
// across themes — e.g. "queen" not "eagle". The board itself is rendered
// through the active theme, so the pieces will look however the user's theme says.

export const PUZZLES = [
  {
    id: 1,
    title: "Queen Checkmate",
    desc: "Deliver checkmate with your queen",
    category: "Checkmate",
    board: [
      [null, null, null, null, "k", null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, "K", null, "Q", null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
    ],
    turn: "white",
    solution: { from: [2, 6], to: [0, 6] },
    hint: "The queen can deliver mate on the back rank",
  },
  {
    id: 2,
    title: "Back Rank Mate",
    desc: "Use your rook to trap the king",
    category: "Checkmate",
    board: [
      [null, null, null, null, null, null, "k", null],
      [null, null, null, null, null, "p", "p", "p"],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, "R", null, null, "K", null],
    ],
    turn: "white",
    solution: { from: [7, 3], to: [0, 3] },
    hint: "The pawns block the king's escape. Charge the back rank!",
  },
  {
    id: 3,
    title: "Knight Fork!",
    desc: "Your knight can attack two pieces at once",
    category: "Tactics",
    board: [
      [null, null, null, "k", null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      ["q", null, null, null, null, null, null, null],
      [null, null, null, "N", null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, "K", null],
    ],
    turn: "white",
    solution: { from: [4, 3], to: [2, 2] },
    hint: "Find a square where the knight attacks both the king and queen",
  },
  {
    id: 4,
    title: "Ladder Mate",
    desc: "Two rooks working together",
    category: "Checkmate",
    board: [
      [null, null, null, null, "k", null, null, null],
      ["R", null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, "R", null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, "K", null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
    ],
    turn: "white",
    solution: { from: [3, 1], to: [0, 1] },
    hint: "One rook cuts off ranks, the other delivers the final blow",
  },
];
